### ISSUE TITLE
数据增强的模型参数问题

### ISSUE THREAD

**Issue by Marquis03** [liujunwen23/MIRE#12]
我有一个7B模型，我用它根据训练数据生成一些数据，然后用这些生成数据和原始数据训练该模型，最后用训练好的模型在测试集上推理。
请问这种情况的参数量是算7B还是算14B？

**Comment by liujunwen23** [comment]
各阶段内的模型参数量分别计算，你的问题算7B

**Comment by Marquis03** [comment]
> 各阶段内的模型参数量分别计算，你的问题算7B

分别计算的话，是不是说明我用于生成数据的模型和用于训练的模型可以是不同的，只要两个阶段用到的模型分别不超过7B就可以？

**Comment by liujunwen23** [comment]
> > 各阶段内的模型参数量分别计算，你的问题算7B
> 
> 分别计算的话，是不是说明我用于生成数据的模型和用于训练的模型可以是不同的，只要两个阶段用到的模型分别不超过7B就可以？

是的

**Comment by Marquis03** [comment]
> > > 各阶段内的模型参数量分别计算，你的问题算7B
> > 
> > 
> > 分别计算的话，是不是说明我用于生成数据的模型和用于训练的模型可以是不同的，只要两个阶段用到的模型分别不超过7B就可以？
> 
> 是的

好的谢谢
