### ISSUE TITLE
测试集伪标签

### ISSUE THREAD

**Issue by vibe-viscot** [liujunwen23/MIRE#14]
能否使用7b模型对测试集推理得到伪标签，将伪标签与训练集一起训练7b模型？（我好像没看到规则里面写，如果不能，请加在天池的规则里面吧）

**Comment by liujunwen23** [comment]
不能。一般机器学习任务中，测试集都不能用于训练。

**Comment by Songjw133** [comment]
> 不能。一般机器学习任务中，测试集都不能用于训练。

希望给个更新一版规则吧，直接白名单标出来那些到底哪些方法是能的。这也不能那也不能，假如到时候又说这个方法不允许用，可页面上也没说啊？
