### ISSUE TITLE
lora参数量

### ISSUE THREAD

**Issue by vibe-viscot** [liujunwen23/MIRE#16]
想确认一下，7b模型，2个lora在推理的时候动态切换，相当于一条测试集样本只会有一个lora在推理，这也算14b嘛，违规的做法？

**Comment by liujunwen23** [comment]
违规。你说的方法和每条测试集用一个7b模型本质类似，不符合比赛要求。

lora参数量相关讨论见：https://github.com/liujunwen23/MIRE/issues/11
