### ISSUE TITLE
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: '213e438b17282904772446704d0b28-0.jpg'

### ISSUE THREAD

**Issue by Chuge0335** [liujunwen23/MIRE#4]
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: '213e438b17282904772446704d0b28-0.jpg'

**Comment by yingyelee** [comment]
我是这么做的 ，可能也有别的更好的方法
train.json 批量替换 image 路径 例如"image": [
            "/xxx/LLaMA-Factory/data/mire/images/212c8bd517276234453407314d1039-0.jpg"
